#!/usr/bin/env python3

r"""Detect the symmetries of a hybridization function and constrain fits to them.

A star-bath model of a hybridization function,

.. math::
    \Delta(z) = \sum_b \frac{A_b}{z - e_b} + C,
    \qquad A_b = V_b^\dagger V_b \succeq 0,\; A_b = A_b^\dagger,

is fitted by a stochastic optimizer, so any symmetry that :math:`\Delta` happens
to possess is only reproduced to within the fit residual unless it is imposed on
the parameters.  This module finds those symmetries and expresses them as
constraints the fit can satisfy *exactly*.

Three families are detected, all of which are **real-linear** conditions on the
Hermitian residues:

* **unitary** (orbital degeneracy, point group) --
  :math:`U^\dagger\Delta(\omega)U = \Delta(\omega)` for all :math:`\omega`,
  so :math:`A_b` and :math:`C` must lie in the \*-algebra generated by the data.
* **antiunitary** (reality, time reversal / Kramers) --
  :math:`\Delta(\omega) = U\Delta(\omega)^{T}U^\dagger`,
  so :math:`A_b = U A_b^{T} U^\dagger`.
* **particle-hole** -- :math:`\Delta(\omega) = -\Delta(-\omega)^*`,
  so the poles are mirrored about the Fermi level with
  :math:`A_{-e} = A_{+e}^{T}` and :math:`C = -C^{T}`.

The first two intersect to a real subspace :math:`S \subset \mathrm{Herm}(n)`,
returned as an orthonormal basis :math:`\{S_p\}` with
:math:`\mathrm{Tr}(S_p S_q) = \delta_{pq}` (real, because the :math:`S_p` are
Hermitian).  Restricting the residues to :math:`S` keeps the inner
variable-projection solve linear, and because :math:`\mathrm{Tr}(S_p S_q)` is a
real Kronecker delta the resulting normal equations decouple across ``p`` -- see
:func:`rspt2spectra.offdiagonal.constrained_inner_solve`.

Particle-hole symmetry additionally pairs the poles.  It is handled by splitting
:math:`S` by transpose parity, :math:`S_p^{T} = \sigma_p S_p`, since a mirror
pair contributes :math:`a_{kp} S_p [1/(z-e_k) + \sigma_p/(z+e_k)]`.

Note that the projection onto :math:`S` preserves positive semi-definiteness:
it is the Reynolds average over a compact group of PSD-preserving isometries, so
the PSD projection used by the fit can be applied before or after it.
"""

from dataclasses import dataclass, field

import numpy as np
import scipy as sp

DEFAULT_SYMMETRY_TOL = 1e-6
"""Default relative tolerance for accepting a symmetry.

Matches :data:`rspt2spectra.h0.BLOCK_EQUIVALENCE_TOL`, and for the same reason:
the measured noise floor between symmetry-equivalent RSPt orbitals is ~1e-10,
while a tolerance tight enough to reject that noise fractures classes that are
physically identical.  The asymmetry matters -- a too-loose tolerance *imposes*
a symmetry the data does not have and silently distorts the fit, whereas a
too-tight one merely falls back to an unconstrained fit.
"""


@dataclass(frozen=True)
class BlockSymmetry:
    """The symmetries of one hybridization block, as constraints on the residues.

    Attributes
    ----------
    basis : (p, n, n) np.ndarray
        Orthonormal Hermitian basis of the allowed residue subspace,
        ``Tr(basis[a] @ basis[b]) == delta_ab``.  ``p == n**2`` means no orbital
        symmetry was found (every Hermitian residue is allowed).
    parity : (p,) np.ndarray
        Transpose parity ``sigma_p`` of each basis element, ``basis[p].T ==
        sigma_p * basis[p]``.  Only meaningful when ``particle_hole`` is set, in
        which case ``basis`` is guaranteed transpose-closed.
    particle_hole : bool
        Whether the bath poles must be mirrored about the Fermi level.
    zero_pole : bool
        Whether the mirrored bath carries an extra unpaired pole pinned at
        ``e = 0`` (used to honour an odd requested state count).
    report : dict
        Human-readable detection diagnostics: measured relative residuals and,
        where a symmetry was detected but not enforced, the reason.
    """

    basis: np.ndarray
    parity: np.ndarray
    particle_hole: bool = False
    zero_pole: bool = False
    report: dict = field(default_factory=dict)

    @property
    def n_imp(self):
        """Number of orbitals in the block."""
        return self.basis.shape[1]

    @property
    def trivial(self):
        """True when no constraint at all is imposed on the residues."""
        return not self.particle_hole and self.basis.shape[0] == self.n_imp**2

    @property
    def even_basis(self):
        """Basis elements with ``S.T == +S`` (only used for particle-hole)."""
        return self.basis[self.parity > 0]

    @property
    def odd_basis(self):
        """Basis elements with ``S.T == -S`` (only used for particle-hole)."""
        return self.basis[self.parity < 0]


def _eigenvalue_tol(tol):
    """Eigenvalue threshold corresponding to a vector tolerance ``tol``.

    ``parity_split`` and ``antiunitary_subspace`` select the fixed set of an
    isometry ``T`` from the eigenvalues of its matrix in an orthonormal basis.
    For a unit vector, ``||T x - x||^2 = 2 (1 - lambda)``, so accepting
    ``|lambda - 1| <= tol`` would only pin the symmetry to ``sqrt(2 tol)`` --
    1.4e-3 at ``tol = 1e-6``, which is nowhere near the "exact, not to within the
    fit residual" guarantee this module exists to provide.  Squaring restores it.
    """
    return 0.5 * tol**2


def full_hermitian_basis(n_imp):
    """Orthonormal basis of all Hermitian ``n_imp x n_imp`` matrices.

    Parameters
    ----------
    n_imp : int
        Matrix dimension.

    Returns
    -------
    (n_imp**2, n_imp, n_imp) np.ndarray
        Orthonormal under ``Tr(S_a S_b)``, transpose-diagonal (each element is
        either symmetric or antisymmetric), so it can be used directly for the
        particle-hole parity split.
    """
    mats = []
    for i in range(n_imp):
        e = np.zeros((n_imp, n_imp), dtype=complex)
        e[i, i] = 1.0
        mats.append(e)
    for i in range(n_imp):
        for j in range(i + 1, n_imp):
            re = np.zeros((n_imp, n_imp), dtype=complex)
            re[i, j] = re[j, i] = 1.0 / np.sqrt(2.0)
            mats.append(re)
            im = np.zeros((n_imp, n_imp), dtype=complex)
            im[i, j] = 1j / np.sqrt(2.0)
            im[j, i] = -1j / np.sqrt(2.0)
            mats.append(im)
    return np.array(mats)


def trivial_symmetry(n_imp):
    """Return the unconstrained :class:`BlockSymmetry` for an ``n_imp`` block.

    Parameters
    ----------
    n_imp : int
        Number of orbitals in the block.

    Returns
    -------
    BlockSymmetry
        Full Hermitian basis, no particle-hole constraint.
    """
    basis = full_hermitian_basis(n_imp)
    return BlockSymmetry(basis=basis, parity=_transpose_parity(basis), particle_hole=False)


def _transpose_parity(basis):
    """Per-element transpose parity of a transpose-diagonal basis, else zeros."""
    parity = np.zeros(basis.shape[0])
    for p, S in enumerate(basis):
        if np.allclose(S.T, S, atol=1e-12):
            parity[p] = 1.0
        elif np.allclose(S.T, -S, atol=1e-12):
            parity[p] = -1.0
    return parity


def _to_real_vec(mats):
    """Map Hermitian matrices to real vectors preserving ``Tr(X Y)`` as a dot product."""
    mats = np.asarray(mats)
    flat = mats.reshape(mats.shape[0], -1)
    return np.concatenate([flat.real, flat.imag], axis=1)


def _from_real_vec(vecs, n_imp):
    """Inverse of :func:`_to_real_vec`."""
    half = n_imp * n_imp
    return (vecs[:, :half] + 1j * vecs[:, half:]).reshape(-1, n_imp, n_imp)


def orthonormal_basis(mats, tol=DEFAULT_SYMMETRY_TOL):
    """Orthonormal basis of the real span of a set of Hermitian matrices.

    Parameters
    ----------
    mats : sequence of (n, n) np.ndarray
        Hermitian matrices, not necessarily independent.
    tol : float
        Singular values below ``tol`` times the largest are treated as zero.

    Returns
    -------
    (p, n, n) np.ndarray
        Orthonormal under ``Tr(S_a S_b)``.  Empty with ``p == 0`` if the span is.
    """
    mats = np.asarray(mats)
    if mats.shape[0] == 0:
        return np.zeros((0,) + mats.shape[1:], dtype=complex)
    n_imp = mats.shape[1]
    V = _to_real_vec(mats)
    _, s, Vh = np.linalg.svd(V, full_matrices=False)
    if s.size == 0 or s[0] == 0:
        return np.zeros((0, n_imp, n_imp), dtype=complex)
    keep = s > tol * s[0]
    return _from_real_vec(Vh[keep], n_imp)


def _compress(hyb, tol):
    """Reduce a frequency-resolved block to at most ``n**2`` independent generators."""
    M, n_imp = hyb.shape[0], hyb.shape[1]
    flat = hyb.reshape(M, n_imp * n_imp)
    _, s, Vh = np.linalg.svd(flat, full_matrices=False)
    if s.size == 0 or s[0] == 0:
        return np.zeros((0, n_imp, n_imp), dtype=complex)
    keep = s > tol * s[0]
    return Vh[keep].reshape(-1, n_imp, n_imp)


def hermitian_algebra_basis(hyb, tol=DEFAULT_SYMMETRY_TOL):
    r"""Hermitian part of the \*-algebra generated by a hybridization block.

    The unitaries that leave every :math:`\Delta(\omega)` invariant form the
    unitary group of the commutant of the data; by the bicommutant theorem the
    matrices invariant under *all* of them are exactly the \*-algebra generated
    by the data and the identity.  That algebra is therefore the largest residue
    subspace compatible with the block's orbital degeneracies, and it always
    contains ``I`` and the data itself, so a fit constrained to it is feasible.

    Parameters
    ----------
    hyb : (M, n, n) np.ndarray
        Hybridization block on a frequency mesh.
    tol : float
        Relative singular-value tolerance for numerical rank decisions.

    Returns
    -------
    (p, n, n) np.ndarray
        Orthonormal Hermitian basis of the generated algebra.
    """
    n_imp = hyb.shape[1]
    gens = _compress(hyb, tol)
    seed = [np.eye(n_imp, dtype=complex)]
    for X in gens:
        seed.append(0.5 * (X + np.conj(X.T)))
        seed.append(0.5j * (np.conj(X.T) - X))
    basis = orthonormal_basis(seed, tol)

    # Close under multiplication.  Products of Hermitian matrices are not
    # Hermitian, so take their Jordan and Lie parts, which span the same algebra.
    while True:
        if basis.shape[0] >= n_imp**2:
            # Already all of Herm(n): nothing can be added, and the closure pass
            # below is the expensive one (it forms p^2 products).  This is the
            # generic, no-symmetry case, so the early exit is the common path --
            # without it a spin-orbit f shell spends tens of seconds here.
            return basis
        extra = []
        for P in basis:
            for Q in basis:
                PQ = P @ Q
                extra.append(0.5 * (PQ + np.conj(PQ.T)))
                extra.append(0.5j * (np.conj(PQ.T) - PQ))
        grown = orthonormal_basis(list(basis) + extra, tol)
        if grown.shape[0] <= basis.shape[0]:
            return basis
        basis = grown


def find_antiunitary(hyb, tol=DEFAULT_SYMMETRY_TOL):
    r"""Find a unitary ``U`` with :math:`\Delta(\omega) = U\Delta(\omega)^{T}U^\dagger`.

    This is the antiunitary (time-reversal-like) symmetry of the block written as
    a condition on the residues, :math:`A_b = U A_b^{T} U^\dagger`.  ``U = I``
    reproduces the statement that the hoppings can be chosen real.

    The defining relation ``U @ D.T == D @ U`` is complex-linear in ``U``, so the
    candidates are the null space of a stacked Kronecker operator.  A
    multi-dimensional null space does not single out a unitary, so every
    candidate is polar-decomposed and then *verified* against the data; if none
    verifies, ``None`` is returned rather than a guess.

    Parameters
    ----------
    hyb : (M, n, n) np.ndarray
        Hybridization block.
    tol : float
        Relative tolerance for both the null space and the verification.

    Returns
    -------
    (n, n) np.ndarray or None
        A verified unitary, or ``None`` when the block has no such symmetry.
    """
    n_imp = hyb.shape[1]
    gens = _compress(hyb, tol)
    if gens.shape[0] == 0:
        return None
    eye = np.eye(n_imp)
    rows = [np.kron(eye, D) - np.kron(D, eye) for D in gens]
    L = np.concatenate(rows, axis=0)
    _, s, Vh = np.linalg.svd(L, full_matrices=False)
    if s.size == 0:
        return None
    scale = s[0] if s[0] > 0 else 1.0
    null = Vh[s <= tol * scale]
    if null.shape[0] == 0:
        return None

    norm = np.linalg.norm(hyb)
    candidates = [null[i].reshape(n_imp, n_imp) for i in range(null.shape[0])]
    if null.shape[0] > 1:
        # A random combination generically avoids the singular members of a
        # degenerate null space; the verification below still gates acceptance.
        rng = np.random.default_rng(0)
        coef = rng.normal(size=null.shape[0]) + 1j * rng.normal(size=null.shape[0])
        candidates.insert(0, (coef @ null).reshape(n_imp, n_imp))
    for U_raw in candidates:
        if not np.any(np.abs(U_raw) > 0):
            continue
        u, _, vh = np.linalg.svd(U_raw)
        U = u @ vh
        residual = np.linalg.norm(hyb - np.einsum("ab, mcb, dc -> mad", U, hyb, np.conj(U)))
        if norm > 0 and residual <= tol * norm:
            return U
    return None


def antiunitary_subspace(basis, U, tol=DEFAULT_SYMMETRY_TOL):
    r"""Restrict a residue basis to :math:`\{X : X = U X^{T} U^\dagger\}`.

    Parameters
    ----------
    basis : (p, n, n) np.ndarray
        Orthonormal Hermitian basis to restrict.
    U : (n, n) np.ndarray
        Unitary from :func:`find_antiunitary`.
    tol : float
        Tolerance on the ``+1`` eigenvalues of the induced involution.

    Returns
    -------
    (q, n, n) np.ndarray
        Orthonormal basis of the invariant subspace, ``q <= p``.
    """
    if basis.shape[0] == 0:
        return basis
    mapped = np.einsum("ab, pcb, dc -> pad", U, basis, np.conj(U))
    R = np.einsum("pij, qji -> pq", basis, mapped).real
    R = 0.5 * (R + R.T)
    lam, vecs = np.linalg.eigh(R)
    keep = np.abs(lam - 1.0) <= _eigenvalue_tol(tol)
    if not np.any(keep):
        return np.zeros((0,) + basis.shape[1:], dtype=complex)
    return np.einsum("pk, pij -> kij", vecs[:, keep], basis)


def parity_split(basis, tol=DEFAULT_SYMMETRY_TOL):
    r"""Intersect a residue basis with its transpose and split it by parity.

    Particle-hole symmetry relates the residues of mirrored poles by a
    transpose, so the allowed subspace must be transpose-closed.  The matrix
    ``M[q, p] = Tr(S_q S_p^T)`` is real symmetric with eigenvalues in
    ``[-1, 1]``; its ``+-1`` eigenvectors span the symmetric and antisymmetric
    parts of ``S & S.T``, and everything in between leaves the subspace under
    transposition and is dropped.

    Parameters
    ----------
    basis : (p, n, n) np.ndarray
        Orthonormal Hermitian basis.
    tol : float
        Tolerance on the ``+-1`` eigenvalues.

    Returns
    -------
    basis : (q, n, n) np.ndarray
        Transpose-closed orthonormal basis.
    parity : (q,) np.ndarray
        ``+1`` for symmetric, ``-1`` for antisymmetric elements.
    """
    if basis.shape[0] == 0:
        return basis, np.zeros(0)
    Mmat = np.einsum("pij, qji -> pq", basis, np.conj(basis)).real
    Mmat = 0.5 * (Mmat + Mmat.T)
    lam, vecs = np.linalg.eigh(Mmat)
    eig_tol = _eigenvalue_tol(tol)
    even = np.abs(lam - 1.0) <= eig_tol
    odd = np.abs(lam + 1.0) <= eig_tol
    parts = []
    parity = []
    if np.any(even):
        parts.append(np.einsum("pk, pij -> kij", vecs[:, even], basis))
        parity.append(np.ones(int(np.count_nonzero(even))))
    if np.any(odd):
        parts.append(np.einsum("pk, pij -> kij", vecs[:, odd], basis))
        parity.append(-np.ones(int(np.count_nonzero(odd))))
    if not parts:
        return np.zeros((0,) + basis.shape[1:], dtype=complex), np.zeros(0)
    return np.concatenate(parts, axis=0), np.concatenate(parity)


def project(basis, A):
    """Orthogonally project Hermitian matrices onto the span of ``basis``.

    Parameters
    ----------
    basis : (p, n, n) np.ndarray
        Orthonormal Hermitian basis.
    A : (..., n, n) np.ndarray
        Matrices to project.

    Returns
    -------
    (..., n, n) np.ndarray
        The projection ``sum_p Re(Tr(S_p A)) S_p``.  Positive semi-definiteness
        is preserved, because the projection is the Reynolds average over a
        compact group of PSD-preserving isometries.
    """
    if basis.shape[0] == 0:
        return np.zeros_like(A)
    coef = np.einsum("pij, ...ji -> ...p", basis, A).real
    return np.einsum("...p, pij -> ...ij", coef, basis)


def _mirror_targets(w, G):
    """Validate a mesh and return the mirrored sample points it can support."""
    w = np.asarray(w, dtype=float)
    G = np.asarray(G)
    if G.shape[0] != len(w):
        raise ValueError(f"w has {len(w)} points but the array has {G.shape[0]} along the frequency axis")
    if len(w) > 1 and not np.all(np.diff(w) > 0):
        raise ValueError("the frequency mesh must be strictly increasing to be mirrored")
    mask = (-w >= w[0]) & (-w <= w[-1])
    return w, G, mask


def mirror_on_mesh(w, G):
    r"""Evaluate a frequency-resolved array at :math:`-\omega`.

    RSPt meshes are neither uniform nor symmetric about the Fermi level, so the
    mirrored value generally has to be interpolated and only the sub-window where
    both :math:`\omega` and :math:`-\omega` are sampled is reported as valid.
    A cubic spline is used where the mesh is long enough to support one; it is
    roughly two orders of magnitude more accurate than linear interpolation on a
    hybridization function, which matters because the interpolation error sets
    the floor on how tightly particle-hole symmetry can be tested at all (see
    :func:`mirror_interpolation_error`).

    Parameters
    ----------
    w : (M,) np.ndarray
        Real frequency mesh, strictly increasing.
    G : (M, ...) np.ndarray
        Values on that mesh.

    Returns
    -------
    mirrored : (M, ...) np.ndarray
        ``G`` evaluated at ``-w``; entries outside the sampled range are zero.
    mask : (M,) np.ndarray of bool
        Points where ``-w`` lies inside the mesh.
    """
    w, G, mask = _mirror_targets(w, G)
    flat = G.reshape(len(w), -1)
    out = np.zeros_like(flat)
    if np.any(mask):
        out[mask] = _interpolate(w, flat, -w[mask], cubic=len(w) >= 4)
    return out.reshape(G.shape), mask


def _interpolate(w, flat, target, cubic):
    """Interpolate the columns of ``flat`` onto ``target``, cubically or linearly."""
    if cubic:
        return sp.interpolate.CubicSpline(w, flat, axis=0)(target)
    out = np.zeros((len(target), flat.shape[1]), dtype=flat.dtype)
    for k in range(flat.shape[1]):
        out[:, k] = np.interp(target, w, flat[:, k].real)
        if np.iscomplexobj(flat):
            out[:, k] = out[:, k] + 1j * np.interp(target, w, flat[:, k].imag)
    return out


def mirror_interpolation_error(w, G):
    r"""Conservative estimate of the error made in evaluating ``G`` at :math:`-\omega`.

    On a mesh symmetric about the Fermi level every mirrored point is itself a
    sample, so the mirror is exact and this is zero.  Otherwise the mirrored
    values are interpolated, and the error is estimated by the difference between
    the cubic interpolant actually used and a linear one -- an overestimate of the
    cubic error, which is the safe direction for a reliability gate.

    This matters because particle-hole symmetry is a statement about
    :math:`\omega` versus :math:`-\omega`: on an asymmetric mesh it simply cannot
    be resolved below the interpolation error, and a test run at a tighter
    tolerance than that would report "not symmetric" for reasons that have
    nothing to do with the physics.

    Parameters
    ----------
    w : (M,) np.ndarray
        Real frequency mesh, strictly increasing.
    G : (M, ...) np.ndarray
        Values on that mesh.

    Returns
    -------
    float
        Absolute error estimate, or ``0.0`` when nothing can be mirrored.
    """
    w, G, mask = _mirror_targets(w, G)
    if not np.any(mask) or len(w) < 4:
        return 0.0
    flat = G.reshape(len(w), -1)
    target = -w[mask]
    return float(np.max(np.abs(_interpolate(w, flat, target, True) - _interpolate(w, flat, target, False))))


def particle_hole_residual(w, hyb):
    r"""Relative violation of :math:`\Delta(\omega) = -\Delta(-\omega)^*`.

    Parameters
    ----------
    w : (M,) np.ndarray
        Real frequency mesh, ascending.
    hyb : (M, n, n) np.ndarray
        Hybridization block.

    Returns
    -------
    float
        ``||Delta(w) + conj(Delta(-w))|| / ||Delta(w)||`` over the sub-window
        symmetric about the Fermi level, or ``inf`` when no such window exists.
    """
    mirrored, mask = mirror_on_mesh(w, hyb)
    if not np.any(mask):
        return np.inf
    ref = hyb[mask]
    norm = np.linalg.norm(ref)
    if norm == 0:
        return np.inf
    return float(np.linalg.norm(ref + np.conj(mirrored[mask])) / norm)


def detect_block_symmetry(w, hyb, tol=DEFAULT_SYMMETRY_TOL, allow_particle_hole=True, ph_data=None):
    """Detect the symmetries of one hybridization block.

    Parameters
    ----------
    w : (M,) np.ndarray
        Real frequency mesh, ascending.
    hyb : (M, n, n) np.ndarray
        Hybridization block on that mesh.  The orbital symmetries are measured
        here, so pass the *fitted* window: a symmetry only needs to hold where
        the model is asked to reproduce the data.
    tol : float
        Relative tolerance; see :data:`DEFAULT_SYMMETRY_TOL`.
    allow_particle_hole : bool
        Set False to detect (and report) particle-hole symmetry without
        enforcing it -- for instance when the fit window excludes ``w > 0``, so
        the mirrored poles would fall outside the fitted region.
    ph_data : tuple, optional
        ``(w_full, hyb_full)`` to measure particle-hole symmetry on, which needs
        both sides of the Fermi level and therefore usually the full mesh.
        Defaults to ``(w, hyb)``.

    Returns
    -------
    BlockSymmetry
        The detected constraints, with measured residuals in ``report``.

    Notes
    -----
    ``zero_pole`` is left False here because it depends on how many bath states
    the block is finally allocated; callers set it with
    :func:`dataclasses.replace` once the allocation is known.
    """
    n_imp = hyb.shape[1]
    report = {}

    basis = hermitian_algebra_basis(hyb, tol)
    if basis.shape[0] == 0:
        basis = full_hermitian_basis(n_imp)
    report["orbital_dim"] = int(basis.shape[0])
    report["orbital_dim_max"] = int(n_imp**2)

    U = find_antiunitary(hyb, tol)
    if U is not None:
        restricted = antiunitary_subspace(basis, U, tol)
        if restricted.shape[0] > 0:
            basis = restricted
            report["antiunitary"] = True
            # U and -U (more generally U up to a phase) define the same
            # antiunitary map, so the identity case must be recognised either way.
            phase = U[np.unravel_index(np.argmax(np.abs(U)), U.shape)]
            normalized = U * (np.abs(phase) / phase)
            report["antiunitary_is_identity"] = bool(np.allclose(normalized, np.eye(n_imp), atol=tol))
    report["residue_dim"] = int(basis.shape[0])

    w_ph, hyb_ph = ph_data if ph_data is not None else (w, hyb)
    ph_residual = particle_hole_residual(w_ph, hyb_ph)
    report["particle_hole_residual"] = ph_residual
    # Particle-hole symmetry compares omega against -omega, so on a mesh that is
    # not symmetric about the Fermi level the mirrored values are interpolated
    # and the symmetry simply cannot be resolved below that interpolation error.
    # Reporting the floor is the honest outcome: a verdict of "not symmetric"
    # taken at a tighter tolerance would be about the mesh, not the physics.
    norm = np.linalg.norm(np.asarray(hyb_ph))
    interp_error = mirror_interpolation_error(w_ph, hyb_ph) / norm if norm > 0 else np.inf
    report["particle_hole_interpolation_error"] = interp_error
    # How much of the mesh the verdict rests on: a window that barely straddles
    # the Fermi level gives a verdict from very few frequencies.
    report["particle_hole_coverage"] = float(np.mean(mirror_on_mesh(np.asarray(w_ph, dtype=float), hyb_ph)[1]))
    particle_hole = bool(ph_residual <= tol)
    if not particle_hole and interp_error > tol:
        report["particle_hole_skipped"] = f"not resolvable on this mesh (interpolation error {interp_error:.1e})"
    if particle_hole and not allow_particle_hole:
        report["particle_hole_skipped"] = "detected but not enforced"
        particle_hole = False

    if particle_hole:
        basis, parity = parity_split(basis, tol)
        if basis.shape[0] == 0:
            # Nothing survives transpose closure; drop the pole mirroring rather
            # than fit an empty model.
            basis = hermitian_algebra_basis(hyb, tol)
            parity = _transpose_parity(basis)
            particle_hole = False
            report["particle_hole_skipped"] = "no transpose-closed residue subspace"
        else:
            report["residue_dim"] = int(basis.shape[0])
    else:
        parity = _transpose_parity(basis)

    return BlockSymmetry(
        basis=basis,
        parity=parity,
        particle_hole=particle_hole,
        report=report,
    )


def describe(sym):
    """One-line human-readable summary of a :class:`BlockSymmetry`.

    Parameters
    ----------
    sym : BlockSymmetry
        The detected symmetry.

    Returns
    -------
    str
        Summary suitable for the verbose fit log.
    """
    rep = sym.report
    parts = [f"residues {rep.get('residue_dim', sym.basis.shape[0])}/{sym.n_imp**2}"]
    if rep.get("antiunitary"):
        parts.append("time-reversal" if not rep.get("antiunitary_is_identity") else "real")
    ph = rep.get("particle_hole_residual")
    if ph is not None and np.isfinite(ph):
        parts.append(f"p-h residual {ph:.2e}")
    if sym.particle_hole:
        parts.append("particle-hole enforced" + (" (+pole at E_F)" if sym.zero_pole else ""))
    elif "particle_hole_skipped" in rep:
        parts.append(f"particle-hole {rep['particle_hole_skipped']}")
    return ", ".join(parts)
